# Generated by Django 4.0.5 on 2022-06-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Gran',
        ),
        migrations.CreateModel(
            name='Granted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('Gran', models.ManyToManyField(related_name='G', to='app.wish')),
            ],
        ),
    ]
