# Generated by Django 4.0.5 on 2022-06-24 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_wish_gran_granted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grantedd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateField(auto_now_add=True)),
                ('updatedAt', models.DateField(auto_now=True)),
                ('Gran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishd', to='app.wish')),
            ],
        ),
        migrations.DeleteModel(
            name='Granted',
        ),
    ]
