# Generated by Django 4.0.5 on 2022-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_granted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
